# Basic Config
substitutions:
  devicename: fridge-relay

esphome:
  name: ${devicename}
  platform: ESP8266
  board: esp01_1m

  on_boot:
    priority: -100.0
    then:
      - script.execute: failsafe

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  baud_rate: 0 # (UART logging interferes with cse7766)

ota:

mqtt:
  broker: home.local

  on_message:
    topic: ${devicename}/keepalive
    then:
      - script.execute: reset_failsafe

script:
  - id: reset_failsafe
    then:
      - script.stop: failsafe
      - script.execute: failsafe
  - id: failsafe
    then:
      - delay: 10min
      - logger.log: Failsafe started
      - while:
          condition:
            lambda: return true;
          then:
            - switch.turn_off: relay
            - delay: 50min
            - switch.turn_on: relay
            - delay: 10min

# Device Specific Config
uart:
  rx_pin: RX
  baud_rate: 4800

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Sonoff S31 Button"
    on_press:
      - switch.toggle: relay
  - platform: status
    name: "Sonoff S31 Status"

sensor:
  - platform: wifi_signal
    name: "Sonoff S31 WiFi Signal"
    update_interval: 60s
  - platform: cse7766
    current:
      name: "Sonoff S31 Current"
      accuracy_decimals: 1
    voltage:
      name: "Sonoff S31 Voltage"
      accuracy_decimals: 1
    power:
      name: "Sonoff S31 Power"
      accuracy_decimals: 1
switch:
  - platform: gpio
    name: "Sonoff S31 Relay"
    pin: GPIO12
    id: relay

status_led:
  pin: GPIO13