version: "3.4"
services:
  fridge:
    build:
      context: .
    image: fridge
    environment:
      - BLINKA_MCP2221=1
      # Negative number = Do not reset on device init
      - BLINKA_MCP2221_RESET_DELAY=-1
      # - DEBUG=1
    devices:
      - /dev/bus/usb
    volumes:
      - /run/avahi-daemon/socket:/run/avahi-daemon/socket
      - /etc/localtime:/etc/localtime:ro
    network_mode: "host"
