version: "3.4"
services:
  mosquitto:
    build:
      context: .
      dockerfile: Dockerfile.mosquitto
    image: mosquitto-config
  homeassistant:
    image: homeassistant/home-assistant:2021.6.6
    ports:
      - 8123:8123
    volumes:
      - /home/fgervais/container_data/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - mosquitto
  fridge:
    build:
      context: .
    image: fridge
    environment:
      - BLINKA_MCP2221=1
      # Do not reset on device init
      - BLINKA_MCP2221_RESET_DELAY=-1
    devices:
      - /dev/bus/usb
    depends_on:
      - mosquitto
